### ISSUE TITLE
error in wallet-derive

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet#53]
$ ./wallet derive --help

var Bitcore = require('bitcore-wallet-client').getBitcore();
                                               ^

TypeError: require(...).getBitcore is not a function
    at Object.<anonymous> (5:48)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by isocolsky** [comment]
Looking into this
